name: Deploy

inputs:
  artifact-name:
    description: Artifact name
    required: false
    default: 'artifact'
  working-directory:
    description: Project directory
    required: false
    default: '.'
  application-name:
    description: Application Name
    required: false
    default: 'application-jar'

runs:
  using: composite
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}

    - name: Placeholder deploy
      shell: bash
      run: echo "CD job will deploy build artifact"